### ISSUE TITLE
New Scaling Action Lacks a Hit formula?

### ISSUE THREAD

**Issue by Winnihym** [Skyl3lazer/giffyglyph-monster-maker-continued#69] opened 2024-09-12 21:54 UTC
Hello, Skyl3lazer!  Thanks for taking on this project; it's an amazing tool.  It looks to me as if in the process of creating a new scaling action, when you go to the damage tab, there are entry fields for miss and versatile, but not for hit.  There is an add radial button that, as far as I can tell, doesn't do anything.  You can add a formula to the miss and that updates in the scaling action, but the versatile does not.

**Comment by Skyl3lazer** [comment] 2024-09-12 22:58
What version of GMMC, Foundry, and dnd5e are you on? Do you see any errors in the console? You're right the "Add" button should let you add a new row, as shown:
![image](https://github.com/user-attachments/assets/5fcc6db9-96dc-46da-bd3f-aabf70e916ae)

**Comment by Winnihym** [comment] 2024-09-13 00:51
GMMC: 1.1.2.2
Foundry: 12/327
DND5e: 3.3.1

Yeah, doesn't do that.
![image](https://github.com/user-attachments/assets/7898ac98-3f60-4646-b597-fc221ca7d640)

**Comment by Skyl3lazer** [comment] 2024-09-13 01:42
This seems to be a new issue in dnd5e 3.3.1 - I'm investigating, and hopefully have a solution for you in the near future. For now you can edit templates from the Attacks folder since they have damage already.

**Comment by Skyl3lazer** [comment] 2024-09-13 02:05
I put a bugfix patch out for this (and one other small fix I had on dev) so if you get latest on GMMC it should be fixed!

**Closed by Skyl3lazer** 2024-09-13 02:05 UTC
Labels: dnd5e version incompat, investigating

**Comment by Winnihym** [comment] 2024-09-13 12:22
I don't know if this will help, but I did notice something subtle this morning.

Before I click on the add button:
![image](https://github.com/user-attachments/assets/e2065677-28c6-4c95-a733-b43993e1b2e4)

After I click on the add button:
There's a red halo around the add button that disappears as soon as I click anywhere else.  (which is why I can't capture an image of it).  Would indicate that the button is live in some fashion.

**Comment by Winnihym** [comment] 2024-09-13 12:43
Thanks!
________________________________

**Comment by Winnihym** [comment] 2024-09-13 13:47
Sorry about this; that bugfix worked great, but there's a new issue; created attacks can't be added to a new scaling monster.  Same problem, the add button doesn't do anything, and you can't drag and drop them onto the creature.  If I try to add them, two things happen.  I can no longer drag and drop compendium attacks onto a new scaling monster (I was able to before I tried to add the new scaling attack I created), and I can no longer open the creature sheet from the actors list by double clicking.  You have to delete the monster and create a new one, and then you can add new compendium attacks, but if you try to add the new scaling attack to it, it doesn't add, and freezes up the creature's sheet.


________________________________

**Comment by Skyl3lazer** [comment] 2024-09-13 13:53
I think this may be a local issue, as testing it right now with the exact versions you listed plus the 1.1.2.3 hotfix those functions work. If you open the console in foundry (f12 in browser), are there any red errors that appear when you press "add"?

Do you have any modules running besides GMMC and libWrapper?

**Comment by Winnihym** [comment] 2024-09-13 15:49
[cid:0cc08393-6a84-4d60-9f06-0d848c621762]

But, I'm running a whole bunch of other mods.  I'll rerun with just libwrapper and GMMC.  Thanks!
________________________________

**Comment by Winnihym** [comment] 2024-09-13 15:55
Okay, this is with just GMMC and Libwrapper (Plus DFreds and MQOL).

I didn't delete the previous scaled monster or scaled action.  Scaled action worked, but the scaled monster did not.  I could delete it, and start a new one, and try to add the scaled action, and got the same result, but I think that's the last error you see, MonsterSheet 34.  MonsterSheet 26-30 were me just trying to click on the pre-existing scaled monster.

[cid:7ee47029-b42d-41dd-acb9-6becd09e2917]
________________________________

**Comment by Winnihym** [comment] 2024-09-16 17:08
Looks like there was a conflict with Tidy5e Sheets module.  Thanks for all the help; everything seems to work now with that mod disabled.

**Comment by Skyl3lazer** [comment] 2024-09-16 17:19
Could you submit that as a second ticket with some screenshots of what's happening? There shouldn't be conflicts between those, they use different sheets entirely.

**Comment by Winnihym** [comment] 2024-09-16 18:43
I will, but not quickly, sorry.  I just left for a work trip and won't be back until the 25th.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Winnihym** [comment] 2024-09-25 17:49
Hi, Skyl3lazer,

I took a look at this this morning, and i can't seem to replicate the problem I was having.  I can make a new scaling action, drag it onto a new scaling monster, and the action scales as the monster does, even with all my mods active.  I'll keep fiddling with it, but I think you can delete the bug report for now.

Do you have a patreon for this project I can support?

Chris
________________________________

**Comment by Skyl3lazer** [comment] 2024-09-25 18:05
Nope, as I am not the original author I didn't set up my own patreon. Check
out giffyglyph's info in the readme.

**Comment by Winnihym** [comment] 2024-09-25 22:04
Okay, found it.

It seems to lock up whenever an equation is used that doesn't have the correct syntax in a shortcode formula.  For instance, if I describe a damage as [cr*level] instead of [cr*level, d6], it then crashes my ability to modify the scaled ability.  It throws an error instead of letting me correct the mistake.

[cid:ef83fc90-bd0c-472d-a16a-afd0c6e9e628]
________________________________

**Comment by Skyl3lazer** [comment] 2024-09-25 22:21
That image doesn't come through, could you post it on GitHub? Or just create a new ticket if you've found a consistent reproduction.

**Comment by Winnihym** [comment] 2024-09-28 18:11
Okay, posted in a new ticket (#70).

I'm also seeing that the DC save for saving throw attacks doesn't seem to change to match the DC save of the creature; is that by  design?  Is there some way to set or amend the DC saving throw for an attack?  For instance, a breath weapon like attack always seems to have a DC10 dexterity save, no matter what the level of the creature is.
________________________________

**Comment by Skyl3lazer** [comment] 2024-09-28 18:23
Change the associated ability for the attack. "Max" will pick the highest
attribute, or you can pick a specific.
