### ISSUE TITLE
Ready set roll compatibility breaks after 1.0.1.2, tested on 1.1.1.3

### ISSUE THREAD

**Issue by narayb** [Skyl3lazer/giffyglyph-monster-maker-continued#62] opened 2024-08-10 20:46 UTC
Ready set roll version is 3.0.14. 5E version is 3.1.2.

When wanting to try out the new update with the maxDie shortcode I ran into the issue that the part of ready set roll that combines attack and damage rolls into one card completely break on GMMC ver1.1.1.3.

I assume something changed in how the data is handled in the monster sheet since ready set roll throws this error:

![image](https://github.com/user-attachments/assets/6b1ce6f8-da71-4de0-958b-7a091d1668a1)

Here I click the Damage button after rolling an attack and then the damage part is not properly combined.

If Ready set roll is set to combine and automatically roll attacks and damage, then the attack roll is completely unable to go off and 5E prompts me to just roll damage.

![image](https://github.com/user-attachments/assets/710f2266-fc9d-48ff-9c57-8a8b6f727fca)

Please fix this if possible, I tried updating RSR, but that wanted me to update 5E and something is broken there too..

Thank you in advance, as always.

**Comment by Skyl3lazer** [comment] 2024-08-12 16:16
I sent a message to the dev for RSR, not sure if this bug is caused by data I pass along or if this is a case RSR doesn't handle well.

**Comment by Skyl3lazer** [comment] 2024-08-12 17:48
Fixed on dev

**Closed by Skyl3lazer** 2024-08-12 17:48 UTC
Labels: bug, mod incompatibility

**Comment by narayb** [comment] 2024-08-12 18:04
Thank you so much!
