### ISSUE TITLE
Can't change monster's current health

### ISSUE THREAD

**Issue by ojmaster** [Skyl3lazer/giffyglyph-monster-maker-continued#25] opened 2024-03-09 01:45 UTC
I am running DnD 5e 3.0.4, I just created a monster and I can't change the current hit points. From the sheet or from the actor token.

**Comment by Skyl3lazer** [comment] 2024-03-09 13:55
Duplicate of #21 . Please use the dev branch for dnd5e 3 for now.

**Closed by Skyl3lazer** 2024-03-09 13:55 UTC
Labels: duplicate
